# Generated by Django 4.0.2 on 2022-02-09 09:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_followpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowPage',
            new_name='Follow',
        ),
    ]
