# Generated by Django 4.0.2 on 2022-02-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usersavepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Branch',
            field=models.CharField(choices=[('Bachelor of Computer Science Engineering', 'Bachelor of Computer Science Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Aeronautical Engineering', 'Aeronautical Engineering'), ('Bachelor of Business Administration', 'Bachelor of Business Administration'), ('Master of Business Administration', 'Master of Business Administration'), ('Hotel Management', 'Hotel Management'), ('Agricultural Science', 'Agricultural Science'), ('Biotechonology', 'Biotechonology'), ('Chemical Engineering', 'Chemical Engineering'), ('Fashion Techonology', 'Fashion Techonology'), ('Master of Business Administration', 'Master of Business Administration'), (None, 'None')], default='None', max_length=100),
        ),
    ]
