# Generated by Django 4.0.2 on 2022-02-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_savepost_delete_likepagepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_profile',
            field=models.ImageField(default='group.png', upload_to='page_profile'),
        ),
    ]
